# Generated by Django 4.0.6 on 2022-07-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Date_added',
            new_name='date_added',
        ),
    ]
